insert into user_table (user_name, password, user_type) values ('root', '123', 1);
insert into user_table (user_name, password, user_type) values ('test1', '123', 1);
insert into user_table (user_name, password, user_type) values ('test2', '123', 1);
insert into user_table (user_name, password, user_type) values ('test3', '123', 1);
insert into message_table (user_id, message) values (1, 'test data1');
insert into message_table (user_id, message) values (1, 'test data2');
insert into message_table (user_id, message) values (1, 'test data3');
insert into message_table (user_id, message) values (1, 'test data4');
insert into message_table (user_id, message) values (1, 'test data5');
insert into message_table (user_id, message) values (1, 'test data6');
insert into message_table (user_id, message) values (1, 'test data11');
insert into message_table (user_id, message) values (1, 'test data12');
insert into message_table (user_id, message) values (1, 'test data13');
insert into message_table (user_id, message) values (1, 'test data14');
insert into message_table (user_id, message) values (1, 'test data15');
insert into message_table (user_id, message) values (1, 'test data16');
insert into message_table (user_id, message) values (1, 'test data21');
insert into message_table (user_id, message) values (1, 'test data22');
insert into message_table (user_id, message) values (1, 'test data23');
insert into message_table (user_id, message) values (1, 'test data24');
insert into message_table (user_id, message) values (1, 'test data25');
insert into message_table (user_id, message) values (1, 'test data26');
insert into message_table (user_id, message) values (1, 'test data31');
insert into message_table (user_id, message) values (1, 'test data32');
insert into message_table (user_id, message) values (1, 'test data33');
insert into message_table (user_id, message) values (1, 'test data34');
insert into message_table (user_id, message) values (1, 'test data35');
insert into message_table (user_id, message) values (1, 'test data36');
insert into message_table (user_id, message) values (1, 'test data41');
insert into message_table (user_id, message) values (1, 'test data42');
insert into message_table (user_id, message) values (1, 'test data43');
insert into message_table (user_id, message) values (1, 'test data44');
insert into message_table (user_id, message) values (1, 'test data45');

